## a) Implementacja binarnej reprezentacji chromosomu + konfiguracja dokładności
- `n` - liczba zmiennych, liczba całkowita
- `bits` - liczba bitów chromosomu, liczba całkowita
- `quantity` - liczba chromosomów, liczba całkowita

In [2]:
import numpy as np

In [3]:
def gen_chromosome(n, bits, quantity = 1):
    return np.random.randint(0,2, size=(quantity, n * bits))

In [4]:
print(gen_chromosome(4,2))

[[1 1 1 1 1 1 1 0]]


## b) Implementacja konfiguracji wielkości populacji
- `n` - liczba zmiennych, liczba całkowita
- `bits` - liczba bitów chromosomu, liczba całkowita
- `popSize` - liczba chromosomów w populacji, liczba całkowita

In [5]:
def gen_population(n, bits, popSize):
    return gen_chromosome(n, bits, popSize)

In [6]:
print(gen_population(4, 2, 20))

[[1 1 1 1 1 0 0 0]
 [0 1 1 1 0 0 0 1]
 [1 0 1 1 1 0 1 0]
 [0 0 0 0 0 0 1 0]
 [0 0 1 1 1 0 1 0]
 [1 0 0 1 1 1 1 1]
 [1 1 0 1 0 0 0 1]
 [0 0 1 1 0 0 1 1]
 [0 0 1 1 0 1 1 1]
 [1 1 1 0 0 1 0 0]
 [1 1 1 0 0 0 0 0]
 [1 0 0 1 0 0 1 0]
 [1 1 1 0 0 1 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 1 1 1 0]
 [1 0 1 1 1 0 0 1]
 [1 1 0 1 1 1 1 1]
 [1 1 0 1 0 1 1 0]
 [1 0 0 0 0 0 0 1]
 [0 0 0 1 1 1 1 1]]


## c) Implementacja konfiguracji liczby epok